@startuml
actor 教师
actor 学生
actor 用户
教师 --|> 用户
学生 --|> 用户

用户 --> (登录)
用户 --> (登出)
用户 --> (查看个人信息)
用户 --> (修改GitHub用户名)
用户 --> (修改密码)

教师 -up-> (评定成绩)
教师 -up-> (查看学生列表)
教师 -up-> (查看学生成绩)
学生 -up-> (查看学生列表)
学生 -up-> (查看个人成绩)
@enduml